# Generated by Django 3.2.8 on 2021-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Associated_KW',
            field=models.CharField(default=('liderazgo', 1), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='source_url',
            field=models.SlugField(default=('liderazgo', 1), max_length=200),
            preserve_default=False,
        ),
    ]
