# Generated by Django 3.2.8 on 2021-10-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20211022_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='item',
            name='information_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vigilance_category',
        ),
    ]
