# Generated by Django 3.2.8 on 2021-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20211022_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
