# Generated by Django 3.2.8 on 2021-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aprendizaje',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='hallazgo',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='paginas',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='relevancia',
            field=models.TextField(blank=True, default=None),
        ),
    ]
