# Generated by Django 3.2.8 on 2021-10-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20211022_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='aprendizaje',
            new_name='finding',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='hallazgo',
            new_name='learning',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='paginas',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='relevancia',
            new_name='relevance',
        ),
    ]
