# Generated by Django 3.2.8 on 2021-10-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_item_languaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='relevance',
            field=models.TextField(default=None),
        ),
    ]
