# Generated by Django 3.2.8 on 2021-10-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_rename_relevance_item_importance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='importance',
            new_name='relevance',
        ),
    ]
