# Generated by Django 3.2.8 on 2021-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_rename_importance_item_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='learning',
            field=models.TextField(blank=True),
        ),
    ]
