# Generated by Django 3.2.8 on 2021-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_item_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='finding',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='learning',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pages',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='relevance',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
