# Generated by Django 3.2.8 on 2021-10-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20211028_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Date',
            field=models.CharField(max_length=30),
        ),
    ]
