# Generated by Django 3.2.8 on 2021-10-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
