# Generated by Django 3.2.8 on 2021-10-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_alter_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='Name',
        ),
        migrations.AddField(
            model_name='target',
            name='Items',
            field=models.ManyToManyField(to='storage.Item'),
        ),
        migrations.AlterField(
            model_name='target',
            name='Base_url',
            field=models.CharField(max_length=200),
        ),
    ]
