# Generated by Django 3.2.8 on 2021-10-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_item_relevance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='relevance',
            new_name='importance',
        ),
    ]
