# Generated by Django 3.2.8 on 2021-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20211023_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='My_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='Trash_section',
            field=models.BooleanField(default=False),
        ),
    ]
