# Generated by Django 3.2.8 on 2021-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_alter_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Title',
            field=models.CharField(max_length=150),
        ),
    ]
