# Generated by Django 3.2.8 on 2021-10-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Url',
            field=models.SlugField(max_length=250),
        ),
    ]
